# Generated by Django 4.2 on 2025-05-09 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('promptID', models.AutoField(primary_key=True, serialize=False)),
                ('imagePrompt', models.CharField(blank=True, max_length=400, null=True)),
                ('textPrompt', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('responseID', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=50)),
                ('feedback', models.IntegerField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paligemma_app.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paligemma_app.prompt')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paligemma_app.response')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('historyID', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paligemma_app.prompt')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paligemma_app.response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
