# Generated by Django 4.2 on 2025-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paligemma_app', '0003_prompt_response_profile_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='imagePrompt',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
